{% set name = "rastervision-pipeline" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rastervision_pipeline-{{ version }}.tar.gz
  sha256: 0f6b4ee44f031ff39d903c976c98e12e29c00a1a4c34c70fbf53dc7578310735
  patches:
    - 0001-fix-imports.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rastervision=rastervision.pipeline.cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click ==6.*
    - everett ==0.9
    - pydantic ==1.2
    - python >=3.6
    - six ==1.11.*
    - typing-extensions ==3.7.4.1
    - urllib3
    - brotlipy

test:
  imports:
    - rastervision.pipeline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/azavea/raster-vision
  summary: The main rastervision package for configuring, defining, and running pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
    - mxr-conda
